[package]
name = "engines"
description = "Traits and structs to be used to create gam3du engines"
version.workspace = true
edition.workspace = true
license.workspace = true
license-file.workspace = true

[dependencies]
wgpu.workspace = true

[lints]
workspace = true
