[package]
name = "gam3du-framework"
version = "0.1.0"
edition.workspace = true
description = "A game engine written for educational purposes. The main goals are learning/teaching software development, ease of use and having fun!"
license-file.workspace = true

[dependencies]
engines.workspace = true
runtimes.workspace = true

# Abstraction layer for the platform's graphics API
wgpu.workspace = true

log.workspace = true
env_logger.workspace = true
winit.workspace = true

[lints]
workspace = true
