[package]
name = "gam3du-framework"
description = "A game engine written for educational purposes. The main goals are learning/teaching software development, ease of use and having fun!"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
winit.workspace = true
serde_json.workspace = true
rand.workspace = true
indexmap.workspace = true

# Abstraction layer for the platform's graphics API
wgpu.workspace = true

log.workspace = true
env_logger.workspace = true

[lints]
workspace = true
